In [1]:
import pandas as pd
data=pd.read_csv(r'C:\Users\nguye\Downloads\aclImdb_v1\imdb_dataset.csv')
data.head()

                                                text  label
0  Bromwell High is a cartoon comedy. It ran at t...      1
1  Homelessness (or Houselessness as George Carli...      1
2  Brilliant over-acting by Lesley Ann Warren. Be...      1
3  This is easily the most underrated film inn th...      1
4  This is not the typical Mel Brooks film. It wa...      1

In [2]:
# lọc ra 1 vài đòn
print(data[1:3])

                                                text  label
1  Homelessness (or Houselessness as George Carli...      1
2  Brilliant over-acting by Lesley Ann Warren. Be...      1

In [3]:
data['text'].unique()

array(['Bromwell High is a cartoon comedy. It ran at the same time as some other programs about school life, such as "Teachers". My 35 years in the teaching profession lead me to believe that Bromwell High\'s satire is much closer to reality than is "Teachers". The scramble to survive financially, the insightful students who can see right through their pathetic teachers\' pomp, the pettiness of the whole situation, all remind me of the schools I knew and their students. When I saw the episode in which a student repeatedly tried to burn down the school, I immediately recalled ......... at .......... High. A classic line: INSPECTOR: I\'m here to sack one of your teachers. STUDENT: Welcome to Bromwell High. I expect that many adults of my age think that Bromwell High is far fetched. What a pity that it isn\'t!',
       'Homelessness (or Houselessness as George Carlin stated) has been an issue for years but never a plan to help those on the street that were once considered human who did everything from going to school, work, or vote for the matter. Most people think of the homeless as just a lost cause while worrying about things such as racism, the war on Iraq, pressuring kids to succeed, technology, the elections, inflation, or worrying if they\'ll be next to end up on the streets.<br /><br />But what if you were given a bet to live on the streets for a month without the luxuries you once had from a home, the entertainment sets, a bathroom, pictures on the wall, a computer, and everything you once treasure to see what it\'s like to be homeless? That is Goddard Bolt\'s lesson.<br /><br />Mel Brooks (who directs) who stars as Bolt plays a rich man who has everything in the world until deciding to make a bet with a sissy rival (Jeffery Tambor) to see if he can live in the streets for thirty days without the luxuries; if Bolt succeeds, he can do what he wants with a future project of making more buildings. The bet\'s on where Bolt is thrown on the street with a bracelet on his leg to monitor his every move where he can\'t step off the sidewalk. He\'s given the nickname Pepto by a vagrant after it\'s written on his forehead where Bolt meets other characters including a woman by the name of Molly (Lesley Ann Warren) an ex-dancer who got divorce before losing her home, and her pals Sailor (Howard Morris) and Fumes (Teddy Wilson) who are already used to the streets. They\'re survivors. Bolt isn\'t. He\'s not used to reaching mutual agreements like he once did when being rich where it\'s fight or flight, kill or be killed.<br /><br />While the love connection between Molly and Bolt wasn\'t necessary to plot, I found "Life Stinks" to be one of Mel Brooks\' observant films where prior to being a comedy, it shows a tender side compared to his slapstick work such as Blazing Saddles, Young Frankenstein, or Spaceballs for the matter, to show what it\'s like having something valuable before losing it the next day or on the other hand making a stupid bet like all rich people do when they don\'t know what to do with their money. Maybe they should give it to the homeless instead of using it like Monopoly money.<br /><br />Or maybe this film will inspire you to help others.',
       'Brilliant over-acting by Lesley Ann Warren. Best dramatic hobo lady I have ever seen, and love scenes in clothes warehouse are second to none. The corn on face is a classic, as good as anything in Blazing Saddles. The take on lawyers is also superb. After being accused of being a turncoat, selling out his boss, and being dishonest the lawyer of Pepto Bolt shrugs indifferently "I\'m a lawyer" he says. Three funny words. Jeffrey Tambor, a favorite from the later Larry Sanders show, is fantastic here too as a mad millionaire who wants to crush the ghetto. His character is more malevolent than usual. The hospital scene, and the scene where the homeless invade a demolition site, are all-time classics. Look for the legs scene and the two big diggers fighting (one bleeds). This movie gets better each time I see it (which is quite often).',
       ...,
       "The basic genre is a thriller intercut with an uncomfortable menage-a-trois. Fellowes has tried to make a lot more out of this, using the lies of the title in order to bring about all manner of small twists, invariably designed to surprise the characters more than the audience.<br /><br />It's really rather messy though. Fellowes doesn't seem interested presenting the thriller elements in a fashion that will keep us seat-edged. Rather his focus is on the moral predicaments themselves.<br /><br />The dialogue is inconsistent, stagey here, vernacular there and with the constant surprise of realism undone by the occasional cliché-landmine. Though there is no fussing over the locations so that the actors can get on with existing in their space the dreadful score can't create a further dimension and often works against the emotional momentum of given set pieces. There's also a very prosaic, dare I say it British feel to the filming. I didn't want to see a document of two successful middle class people caught in an extraordinary situation, I wanted to see some sort of artful recounting of the story.<br /><br />Finally it is, in fact, the story which lets the rest down. Just as the elements of suspense are rather flat so the story is an asymmetric sum of subplots of different shapes and sizes, woven as a vehicle for character examination. Wilkinson and Watson support this meta-essay with good performances and John Warnaby's ebullient colleague Simon to Wilkinson is a welcome foil for much of the brow-furrowing.<br /><br />I'm disappointed; not that it's bad, but that it could have been much better. 3/10",
       'Four things intrigued me as to this film - firstly, it stars Carly Pope (of "Popular" fame), who is always a pleasure to watch. Secdonly, it features brilliant New Zealand actress Rena Owen. Thirdly, it is filmed in association with the New Zealand Film Commission. Fourthly, a friend recommended it to me. However, I was utterly disappointed. The whole storyline is absurd and complicated, with very little resolution. Pope\'s acting is fine, but Owen is unfortunately under-used. The other actors and actresses are all okay, but I am unfamiliar with them all. Aside from the nice riddles which are littered throughout the movie (and Pope and Owen), this film isn\'t very good. So the moral of the story is...don\'t watch it unless you really want to.',
       'David Bryce\'s comments nearby are exceptionally well written and informative as almost say everything I feel about DARLING LILI. This massive musical is so peculiar and over blown, over produced and must have caused ruptures at Paramount in 1970. It cost 22 million dollars! That is simply irresponsible. DARLING LILI must have been greenlit from a board meeting that said "hey we got that Pink Panther guy and that Sound Of Music gal... lets get this too" and handed over a blank cheque. The result is a hybrid of GIGI, ZEPPELIN, HALF A SIXPENCE, some MGM 40s song and dance numbers of a style (daisies and boaters!) so hopelessly old fashioned as to be like musical porridge, and MATA HARI dramatics. The production is colossal, lush, breathtaking to view, but the rest: the ridiculous romance, Julie looking befuddled, Hudson already dead, the mistimed comedy, and the astoundingly boring songs deaden this spectacular film into being irritating. LILI is like a twee 1940s mega musical with some vulgar bits to spice it up. STAR! released the year before sadly crashed and now is being finally appreciated for the excellent film is genuinely is... and Andrews looks sublime, mature, especially in the last half hour......but LILI is POPPINS and DOLLY frilly and I believe really killed off the mega musical binge of the 60s..... and made Andrews look like Poppins again... which I believe was not Edwards intention. Paramount must have collectively fainted when they saw this: and with another $20 million festering in CATCH 22, and $12 million in ON A CLEAR DAY and $25 million in PAINT YOUR WAGON....they had a financial abyss of CLEOPATRA proportions with $77 million tied into 4 films with very uncertain futures. Maybe they should have asked seer Daisy Gamble from ON A CLEAR DAY ......LILI was very popular on immediate first release in Australia and ran in 70mm cinemas for months but it failed once out in the subs and the sticks and only ever surfaced after that on one night stands with ON A CLEAR DAY as a Sunday night double. Thank god Paramount had their simple $1million (yes, ONE MILLION DOLLAR) film LOVE STORY and that $4 million dollar gangster pic THE GODFATHER also ready to recover all the $77 million in just the next two years....for just $5m.... incredible!'],
      dtype=object)

In [4]:
data['label'].value_counts()

label
1    25000
0    25000
Name: count, dtype: int64

In [5]:
import re
import html
import unicodedata
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# tải dữ liệu NLP cần thiết 
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

STOPWORDS = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\nguye\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [6]:
def clean_text_svm(text):
    """
    Làm sạch text cho mô hình truyền thống như SVM, Logistic Regression.
    - Xóa HTML, ký tự đặc biệt, stopwords
    - Lemmatize để chuẩn hóa từ
    - Giữ lại chỉ các từ có ý nghĩa
    """
    # 1️ Giải mã ký tự HTML (ví dụ &amp; → &)
    text = html.unescape(text)

    # 2️ Loại bỏ thẻ HTML (<br />, <p>, ...)
    text = re.sub(r'<.*?>', ' ', text)

    # 3️ Đưa về chữ thường
    text = text.lower()

    # 4️ Chuẩn hóa Unicode (PokĂ©mon → Pokemon)
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("utf-8", "ignore")

    # 5️ Bỏ ký tự không phải chữ cái
    text = re.sub(r'[^a-z\s]', ' ', text)

    # 6️ Thu gọn khoảng trắng
    text = re.sub(r'\s+', ' ', text).strip()

    # 7️ Tokenization
    tokens = word_tokenize(text)

    # 8️ Bỏ stopwords
    tokens = [w for w in tokens if w not in STOPWORDS]

    # 9️ Lemmatization
    tokens = [lemmatizer.lemmatize(w) for w in tokens]

    #  Ghép lại
    return " ".join(tokens)

In [7]:
svm_data = data['text'].apply(clean_text_svm)

In [8]:
print(svm_data.head(10))

0    bromwell high cartoon comedy ran time program ...
1    homelessness houselessness george carlin state...
2    brilliant acting lesley ann warren best dramat...
3    easily underrated film inn brook cannon sure f...
4    typical mel brook film much less slapstick mov...
5    comedic robin williams quirky insane robin wil...
6    yes art successfully make slow paced thriller ...
7    critically acclaimed psychological thriller ba...
8    night listener robin williams toni collette bo...
9    know robin williams god bless constantly shoot...
Name: text, dtype: object

In [9]:
print(svm_data[0])

bromwell high cartoon comedy ran time program school life teacher year teaching profession lead believe bromwell high satire much closer reality teacher scramble survive financially insightful student see right pathetic teacher pomp pettiness whole situation remind school knew student saw episode student repeatedly tried burn school immediately recalled high classic line inspector sack one teacher student welcome bromwell high expect many adult age think bromwell high far fetched pity

In [10]:
svm_df = pd.DataFrame({
    'text': svm_data,
    'label': data['label']
})

In [11]:
svm_df.head()

                                                text  label
0  bromwell high cartoon comedy ran time program ...      1
1  homelessness houselessness george carlin state...      1
2  brilliant acting lesley ann warren best dramat...      1
3  easily underrated film inn brook cannon sure f...      1
4  typical mel brook film much less slapstick mov...      1

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import LinearSVC
import numpy as np
import time
import os
from sklearn.metrics import  (
    accuracy_score,
    classification_report,
    f1_score,
    precision_score,
    recall_score,
    confusion_matrix
)
import numpy as np

In [19]:
tfidf = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1,2),
    min_df=3,
    max_df=0.9
)

In [20]:

X = tfidf.fit_transform(svm_df['text'])
y = svm_df['label']

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

accuracies = []
f1_scores = []
precisions = []
recalls = []
train_times = []
fold = 1

for train_index, val_index in skf.split(X, y):
    print(f"\n===== Fold {fold} =====")

    X_train, X_val = X[train_index], X[val_index]
    y_train = y.iloc[train_index] if hasattr(y, "iloc") else y[train_index]
    y_val   = y.iloc[val_index]   if hasattr(y, "iloc") else y[val_index]

    model = LinearSVC(C=1.0, random_state=42)

    # Train time
    start = time.time()
    model.fit(X_train, y_train)
    end = time.time()
    train_times.append(end - start)
    print(f"Train time: {end - start:.4f} seconds")

    # Predict
    y_pred = model.predict(X_val)

    # Print sample predictions
    print("----- 5 samples in this fold -----")
    num_samples = min(5, len(val_index))

    for i in range(num_samples):
        real_idx = val_index[i]
        print("-----")
        print(f"Text: {svm_df['text'].iloc[real_idx]}")
        print(f"Label thật: {svm_df['label'].iloc[real_idx]}")
        print(f"Dự đoán: {y_pred[i]}")

    # Metrics
    acc = accuracy_score(y_val, y_pred)
    accuracies.append(acc)

    f1 = f1_score(y_val, y_pred, average='macro')
    f1_scores.append(f1)

    prec = precision_score(y_val, y_pred, average='macro')
    precisions.append(prec)

    rec = recall_score(y_val, y_pred, average='macro')
    recalls.append(rec)

    print(f"Accuracy: {acc:.4f}")
    print(f"F1-macro: {f1:.4f}")
    print(f"Precision-macro: {prec:.4f}")
    print(f"Recall-macro: {rec:.4f}")

    # ===== CONFUSION MATRIX for this fold =====
    cm = confusion_matrix(y_val, y_pred)
    print("\nConfusion Matrix for this fold:")
    print(cm)

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_val, y_pred, digits=4))

    fold += 1


# ===== FINAL SUMMARY =====
print("\n==============================")
print(f"Average Accuracy 5-fold: {np.mean(accuracies):.4f}")
print(f"Accuracy STD: {np.std(accuracies):.4f}")
print("------------------------------")
print(f"Average F1-macro: {np.mean(f1_scores):.4f}")
print(f"F1 STD: {np.std(f1_scores):.4f}")
print("------------------------------")
print(f"Average Precision: {np.mean(precisions):.4f}")
print(f"Average Recall: {np.mean(recalls):.4f}")
print("------------------------------")
print(f"Average train time: {np.mean(train_times):.4f} seconds")
print("==============================")

===== Fold 1 =====
Train time: 1.4820 seconds
----- 5 samples in this fold -----
-----
Text: night listener robin williams toni collette bobby cannavale rory culkin joe morton sandra oh john cullum lisa emery becky ann baker dir patrick stettner hitchcockian suspenser give williams stand low key performance celebrity fan near paranoia one associate almost norm latest derange fan scenario based true event less williams star talk radio personality named gabriel one read story penned airwave accumulated interesting fan form young boy named pete logand culkin submitted manuscript travail troubled youth one editor ashe morton give one read one naturally disturbed ultimately intrigued nightmarish existence pete abducted sexually abused year finally rescued nurse named donna collette giving excellent performance adopted boy correspondence one reveals pete dying aid naturally one want meet fan suddenly doubt possibly devious ulterior motif seed planted estranged lover jess cannavale whose sudden departure new york city apartment one emotional tailspin grown tempest teacup decides investigating donna pete background discovering truth anticipate written armistead maupin co wrote screenplay former lover terry anderson film novice director stettner based true story fan hoax found hitchcockian moment run full tilt like good old fashioned pot boiler help williams give stand low key performance conflicted good hearted personality genuinely want believe number one fan fact real love one thing escaped reality unsettling dreadful moment creepy collette whose one physical trait leave unmentioned underline desperation character rattle core however film run gas eventually becomes bit repetitive predictable despite finely directed piece hoodwink mystery stettner pay listen inner voice careful hope
Label thật: 1
Dự đoán: 1
-----
Text: liked film action scene interesting tense well done especially liked opening scene semi truck tense action scene seemed well done transitional scene filmed interesting way time lapse photography unusual color interesting angle also film funny several part also liked evil guy portrayed give film
Label thật: 1
Dự đoán: 1
-----
Text: night listener probably one william best role make interesting character somewhat odd different movie guarantee never seen kind movie people maybe like slow pacing movie think great plus movie definitely one top movie come year intriguing performance movie great content dramatic feeling americanized movie neither predictable movie feel movie secret hard time determine outcome may excellent movie everything hell damn good original movie
Label thật: 1
Dự đoán: 1
-----
Text: legendary boris karloff ended illustrious career making four cheapie fright flick clunkers mexico token moody period gothic horror entry bunch karloff give typically spry dignified performance matthias morteval elderly eccentric patriarch invite several petty greedy backbiting count relative creepy rundown castle reading pretty soon hateful guest getting bumped lethal life sized toy people populate place onetime mexican sex symbol andres garcia tintorera infamy portrays dashing police officer hero julissa look absolutely ravishing sole likable female character clunky plodding non direction trite number script ugly washed cinematography ridiculous murder set piece gross fat slob get blasted right face miniature cannon overwrought string score morbid gloom doom atmosphere largely lousy acting karloff notably excepted cheesy mild gore poor dubbing rousing fiery conclusion lend enjoyably awful lemon certain endearingly cruddy hence oddly amusing ratty charm real campy hoot
Label thật: 1
Dự đoán: 0
-----
Text: without kirsten miller project completed however awe inspiring beauty talent miss miller would definitely recommend looked actor playing strong performance wagner dismal attempt honor film bit disappointing scene detract entertained mostly criticism writing plot line group talent assembled heroic job salvaging disaster charismatic miller delivery timing impeccable believable play fine line assertive bossy never offensive fact structural engineer claim wish seen big screen ala fortunate rent lost
Label thật: 1
Dự đoán: 0
Accuracy: 0.8935
F1-macro: 0.8935
Precision-macro: 0.8935
Recall-macro: 0.8935

Confusion Matrix for this fold:
[[4461  539]
 [ 526 4474]]

Classification Report:
              precision    recall  f1-score   support

           0     0.8945    0.8922    0.8934      5000
           1     0.8925    0.8948    0.8936      5000

    accuracy                         0.8935     10000
   macro avg     0.8935    0.8935    0.8935     10000
weighted avg     0.8935    0.8935    0.8935     10000


===== Fold 2 =====
Train time: 1.4720 seconds
----- 5 samples in this fold -----
-----
Text: bromwell high cartoon comedy ran time program school life teacher year teaching profession lead believe bromwell high satire much closer reality teacher scramble survive financially insightful student see right pathetic teacher pomp pettiness whole situation remind school knew student saw episode student repeatedly tried burn school immediately recalled high classic line inspector sack one teacher student welcome bromwell high expect many adult age think bromwell high far fetched pity
Label thật: 1
Dự đoán: 1
-----
Text: brilliant acting lesley ann warren best dramatic hobo lady ever seen love scene clothes warehouse second none corn face classic good anything blazing saddle take lawyer also superb accused turncoat selling bos dishonest lawyer pepto bolt shrug indifferently lawyer say three funny word jeffrey tambor favorite later larry sander show fantastic mad millionaire want crush ghetto character malevolent usual hospital scene scene homeless invade demolition site time classic look leg scene two big digger fighting one bleeds movie get better time see quite often
Label thật: 1
Dự đoán: 1
-----
Text: comedic robin williams quirky insane robin williams recent thriller fame hybrid classic drama without dramatization mixed robin new love thriller thriller per se mystery suspense vehicle williams attempt locate sick boy keeper also starring sandra oh rory culkin suspense drama play pretty much like news report william character get close achieving goal must say highly entertained though movie fails teach guide inspect amuse felt like watching guy williams actually performing action third person perspective word felt real able subscribe premise story worth watch though definitely friday saturday night fare rate fiend
Label thật: 1
Dự đoán: 1
-----
Text: yes art successfully make slow paced thriller story unfolds nice volume even notice happening fine performance robin williams sexuality angle film seem unnecessary probably affect much enjoy film however core plot engaging movie rush onto still grip enough keep wondering direction good use light achieve desired affect suspense unexpectedness good nice time watch looking lay back hear thrilling short story
Label thật: 1
Dự đoán: 1
-----
Text: know robin williams god bless constantly shooting foot lately dumb comedy done decade perhaps exception death smoochy bombed came cult classic drama made lately fantastic especially insomnia one hour photo night listener despite mediocre review quick dvd release among best work period chilling story even though include serial killer anyone physically dangerous matter concept film based actual case fraud still yet officially confirmed high school read autobiography child named anthony godby johnson suffered horrific abuse eventually contracted aid result moved story read report online johnson may actually exist saw movie confused feeling robin williams brilliantly portrayed resurfaced mind toni collette probably give best dramatic performance ultimately sociopathic caretaker role far cry movie like little miss sunshine even time looked camera thought staring right take good actress play sort role understated yet well reviewed role make toni collette probably one best actress generation even nominated academy award incredible least one woman world like scary good dark film highly recommend prepared unsettled though movie leaf strange feeling end
Label thật: 1
Dự đoán: 1
Accuracy: 0.8955
F1-macro: 0.8955
Precision-macro: 0.8957
Recall-macro: 0.8955

Confusion Matrix for this fold:
[[4419  581]
 [ 464 4536]]

Classification Report:
              precision    recall  f1-score   support

           0     0.9050    0.8838    0.8943      5000
           1     0.8865    0.9072    0.8967      5000

    accuracy                         0.8955     10000
   macro avg     0.8957    0.8955    0.8955     10000
weighted avg     0.8957    0.8955    0.8955     10000


===== Fold 3 =====
Train time: 1.6302 seconds
----- 5 samples in this fold -----
-----
Text: easily underrated film inn brook cannon sure flawed give realistic view homelessness unlike say citizen kane gave realistic view lounge singer titanic gave realistic view italian idiot many joke fall flat still film lovable way many comedy pull story traditionally reviled member society truly impressive fisher king crap either complaint brook cast someone else lead love mel director writer much lead
Label thật: 1
Dự đoán: 1
-----
Text: typical mel brook film much less slapstick movie actually plot followable leslie ann warren made movie fantastic rated actress moment could fleshed bit scene could probably cut make room worth price rent see acting good overall brook good job without characteristic speaking directly audience warren best actor movie fume sailor played part well
Label thật: 1
Dự đoán: 1
-----
Text: critically acclaimed psychological thriller based true event gabriel robin williams celebrated writer late night talk show host becomes captivated harrowing story young listener adoptive mother toni collette troubling question arise boy story however gabriel find drawn widening mystery hide deadly secret according film official synopsis really stop reading comment watch film lose leg ending m collette planning new life chopped sent deleted scene land overkill true nature physical mental ailment obvious time mr williams return new york possibly blindness could question revelation could made certain either highway video tape scene film would benefit editing director cut williams bobby cannavale jess seem initially believable couple scene two establishing relationship might helped set stage otherwise cast exemplary williams offer exceptionally strong characterization gay impersonation sandra oh anna joe morton ashe rory culkin pete logand perfect best collette donna belongs creepy hall fame m oh correct saying collette might know like guy psycho several year organization giving acting award seemed reach woman due slighter dispersion role certainly could noticed collette award consideration good director patrick stettner definitely evokes hitchcock even make getting sandwich vending machine suspenseful finally writer stettner armistead maupin terry anderson deserve gratitude flight attendant everywhere night listener patrick stettner robin williams toni collette sandra oh rory culkin
Label thật: 1
Dự đoán: 1
-----
Text: like one previous commenters said foundation great movie something happened way delivery waste collette performance eerie williams believable kept waiting get better think bad editing needed another director could film came across canadian movie something like first season x file cheap hokey also needed little suspense something make jump seat movie reached moment faded away kind like false climax see suspenseful would taken away reality story thought part reached gabriel hospital looking boy movie need director cut try fix problem
Label thật: 1
Dự đoán: 0
-----
Text: tale based two edgar allen poe piece fall house usher dance death poem actually quite creepy beginning end similar old black white movie people meet old decrepit house example cat canary old dark house night terror boris karloff play demented inventor life size doll terrorize guest dy early film resident house subjected number terrifying experience go much detail definitely must see fan old dark house mystery watch plenty popcorn soda darkened room dan basinger
Label thật: 1
Dự đoán: 1
Accuracy: 0.8971
F1-macro: 0.8971
Precision-macro: 0.8971
Recall-macro: 0.8971

Confusion Matrix for this fold:
[[4468  532]
 [ 497 4503]]

Classification Report:
              precision    recall  f1-score   support

           0     0.8999    0.8936    0.8967      5000
           1     0.8943    0.9006    0.8975      5000

    accuracy                         0.8971     10000
   macro avg     0.8971    0.8971    0.8971     10000
weighted avg     0.8971    0.8971    0.8971     10000


===== Fold 4 =====
Train time: 1.2574 seconds
----- 5 samples in this fold -----
-----
Text: enjoyed night listener much one better movie summer robin williams give one best performance fact entire cast good played right note character much little sandra oh add wonderful comic touch toni collette great mom never go top everyone believable short movie hour half noticed general release version nine minute shorter sundance version wonder disturbing image cut movie director told story straightforward fashion refreshing change many director day seem think job impress audience rather tell story tell well sucker punched preview ad hitchcockian thriller see night listener want see good story told well go expecting hitchcock disappointed complaint movie ending director could left little audience imagination minor quibble
Label thật: 1
Dự đoán: 1
-----
Text: aro tolbukhin burnt alive seven people mission guatemala also declared murdered another people used kill pregnant woman set fire movie documentary portrait personality aro several interview people got know scene played actor based real fact aro tolbukhin serious work analytical morbid horrifying testimony childhood trauma turn man monster rate
Label thật: 1
Dự đoán: 1
-----
Text: got unique twist two genre ever seen giant monster movie genre living mummy movie genre unique blend make unique compelling story cast outstanding including tom bosley far know never horror movie ever effect impressive idea giant mummy filled smaller mummy cool one one complaint wish saw giant mummy think great job dialog character story perfect acting wonderful got best movie come sci fi channel heard best movie come sci fi channel give fallen one
Label thật: 1
Dự đoán: 1
-----
Text: people bitch movie awful movie like godfather titanic greatest movie st century great acting directing effect music generally everything movie always dumped one day one said like world decided agree nothing wrong movie say movie heavily oscar awarded movie time money ever made ever sadly one underrated movie ever seen apart truly best movie time movie come close like star war lord ring trilogy anything master hitchcock spielberg tim burton good movie director none match james cameron masterpiece titanic
Label thật: 1
Dự đoán: 1
-----
Text: think james cameron might becoming favorite director second review movie anyway everyone remembers rms titanic big fast unsinkable april news one biggest tragedy ever well james cameron decided make movie star two fictional character spotlight instead ship well onto main review let remind opinion zero fact fact present event film two main character jack leonardo dicaprio rose kate winslet annoying much watch find could become annoying http tinyurl com ojhoyn main villain guess bad luck fate hand god blasphemy intended plain caledon hockley billy zane combine get oh yes get love story sinking boat supporting character following personal favorite mr andrew victor garber idk nice lovejoy david warner murdoch ewan stewart lightoller jonathan phillips captain smith bernard hill molly brown kathy bates many also got present day treasure hunter brock lovett bill paxton add something story something good action awesome especially second half drama also good end eye dropping rainstorm silent tear story simple work treasure hunter seek heart ocean instead find drawing woman wearing said diamond call tell tale rms titanic two lover separated social class ultimately fate ship everything story work flaw give titanic awesome
Label thật: 1
Dự đoán: 1
Accuracy: 0.8967
F1-macro: 0.8967
Precision-macro: 0.8967
Recall-macro: 0.8967

Confusion Matrix for this fold:
[[4464  536]
 [ 497 4503]]

Classification Report:
              precision    recall  f1-score   support

           0     0.8998    0.8928    0.8963      5000
           1     0.8936    0.9006    0.8971      5000

    accuracy                         0.8967     10000
   macro avg     0.8967    0.8967    0.8967     10000
weighted avg     0.8967    0.8967    0.8967     10000


===== Fold 5 =====
Train time: 1.6452 seconds
----- 5 samples in this fold -----
-----
Text: homelessness houselessness george carlin stated issue year never plan help street considered human everything going school work vote matter people think homeless lost cause worrying thing racism war iraq pressuring kid succeed technology election inflation worrying next end street given bet live street month without luxury home entertainment set bathroom picture wall computer everything treasure see like homeless goddard bolt lesson mel brook directs star bolt play rich man everything world deciding make bet sissy rival jeffery tambor see live street thirty day without luxury bolt succeeds want future project making building bet bolt thrown street bracelet leg monitor every move step sidewalk given nickname pepto vagrant written forehead bolt meet character including woman name molly lesley ann warren ex dancer got divorce losing home pal sailor howard morris fume teddy wilson already used street survivor bolt used reaching mutual agreement like rich fight flight kill killed love connection molly bolt necessary plot found life stink one mel brook observant film prior comedy show tender side compared slapstick work blazing saddle young frankenstein spaceballs matter show like something valuable losing next day hand making stupid bet like rich people know money maybe give homeless instead using like monopoly money maybe film inspire help others
Label thật: 1
Dự đoán: 1
-----
Text: first read armistead maupins story taken human drama displayed gabriel one care love said given film version excellent story expected see past gloss hollywood writer armistead maupin director patrick stettner truly succeeded right amount restraint robin williams capture fragile essence gabriel let u see struggle issue trust personnel life jess world around donna introduced player drama reminded nothing ever seems smallest event change life irrevocably request review book written young man turn life changing event help gabriel find strength within carry move forward bad people avoid film say average american probably think robin williams serious role work please give movie chance robin williams touch darkness must find go better people like movie one hour photo stepped actor made another quality piece art oh forget believe bobby cannavale jess steal every scene leading man look screen presence hack opinion could carry movie right
Label thật: 1
Dự đoán: 1
-----
Text: night listener held attention robin williams shining new york city radio host becomes enamored friendship year old boy rory culkin ill williams never met boy person contact talking telephone however williams ex boyfriend nice job bobby cannavale raise doubt boy prompt williams arrange meeting person follows make permanent impact williams way expect leave toni collette also star enjoyed film toni collette giving memorable portrayal culkin adoptive mother sandra oh also starred williams friend night listener inspired actual event somber almost creepy silence throughout time predictable thanks review read seeing movie due logic liked anyway enjoy williams role like comedic character added bonus recommended
Label thật: 1
Dự đoán: 1
-----

In [21]:
from sklearn.svm import LinearSVC
import joblib

# Train lại toàn bộ data
final_model = LinearSVC(C=1.0, random_state=42)
final_model.fit(X, y)

LinearSVC(random_state=42)

In [22]:
# Lưu model
joblib.dump(final_model, "svm_model.pkl")

# Lưu TF-IDF vectorizer
joblib.dump(tfidf, "tfidf.pkl")

['tfidf.pkl']